// flow-typed signature: 4019099e329f1508984c21c9b99b0310
// flow-typed version: <<STUB>>/@auth0/auth0-spa-js_v^1.6.3/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@auth0/auth0-spa-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@auth0/auth0-spa-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@auth0/auth0-spa-js/dist/auth0-spa-js.development' {
  declare module.exports: any;
}

declare module '@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm' {
  declare module.exports: any;
}

declare module '@auth0/auth0-spa-js/dist/auth0-spa-js.production' {
  declare module.exports: any;
}

declare module '@auth0/auth0-spa-js/dist/lib/auth0-spa-js.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@auth0/auth0-spa-js/dist/auth0-spa-js.development.js' {
  declare module.exports: $Exports<'@auth0/auth0-spa-js/dist/auth0-spa-js.development'>;
}
declare module '@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js' {
  declare module.exports: $Exports<'@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm'>;
}
declare module '@auth0/auth0-spa-js/dist/auth0-spa-js.production.js' {
  declare module.exports: $Exports<'@auth0/auth0-spa-js/dist/auth0-spa-js.production'>;
}
declare module '@auth0/auth0-spa-js/dist/lib/auth0-spa-js.cjs.js' {
  declare module.exports: $Exports<'@auth0/auth0-spa-js/dist/lib/auth0-spa-js.cjs'>;
}
