language: node_js

node_js:
  - "10"

#script: npm test
script:
#  - echo "Branch: ($TRAVIS_BRANCH) PR: ($TRAVIS_PULL_REQUEST) Tag: ($TRAVIS_TAG)"
  - npm test
  if: branch != master
#    (branch = master AND type = push) OR \
#    (branch != master AND type = pull_request)

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master
