---
language: node_js

node_js:
  - "10"

jobs:
  include:
    - stage: test
      script:
        - echo $TRAVIS_BRANCH : $TRAVIS_PULL_REQUEST
        - npm test
    - stage: deploy
      script: ./scripts/deploy.sh
