---
language: node_js

node_js:
  - "10"

jobs:
  include:
    - stage: test
      script:
        echo "Kevin"
        echo $TRAVIS_BRANCH - $TRAVIS_PULL_REQUEST - $TRAVIS_TAG
        npm test
    - stage: deploy
      script: ./scripts/deploy.sh

stages:
  - name: test
  - name: deploy
    if: branch = master
