---
language: node_js

node_js:
  - "10"

jobs:
  include:
  - stage: test
    script:
      - npm test
    if: type = pull_request
  - stage: deploy
    script:
      - npm test
      - ./scripts/deploy.sh
    if: type = push AND branch = master
