---
language: node_js

node_js:
  - "10"

jobs:
  include:
    if: type = pull_request OR (type = push AND branch = "master")

script:
  - echo TRAVIS_BRANCH - $TRAVIS_BRANCH
  - echo TRAVIS_PULL_REQUEST - $TRAVIS_PULL_REQUEST
  - echo TRAVIS_PULL_REQUEST_BRANCH - $TRAVIS_PULL_REQUEST_BRANCH
  - echo TRAVIS_EVENT_TYPE - $TRAVIS_EVENT_TYPE
