---
language: node_js

node_js:
  - "10"

jobs:
  include:
    - stage: test
      script: echo "Kevin"; npm test;
    - stage: deploy
      script: ./scripts/deploy.sh

stages:
  - test
  - name: deploy
    if: branch = master
