language: node_js
node_js:
- '10'
jobs:
  include:
  - stage: Test PR
    script:
    - npm test
    if: type = pull_request
  - stage: Deploy latest code
    script:
    - "./.travis/deploy.sh"
    if: type = push AND branch = master
addons:
  ssh_known_hosts:
  - 45.79.110.249
