---
language: node_js

node_js:
  - "10"

jobs:
  include:
  - node_js: "10"
    on: branch = "master"

script:
  - echo TRAVIS_BRANCH - $TRAVIS_BRANCH
  - echo TRAVIS_PULL_REQUEST - $TRAVIS_PULL_REQUEST
  - echo TRAVIS_PULL_REQUEST_BRANCH - $TRAVIS_PULL_REQUEST_BRANCH
  - echo TRAVIS_EVENT_TYPE - $TRAVIS_EVENT_TYPE
