version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-${FLAVOR}
    volumes:
      - /var/cert/royk.us:/var/cert/royk.us
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["yarn", "run", "docker:${FLAVOR}:web"]
    depends_on:
      - api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api:
    build:
      context: .
      dockerfile: Dockerfile-${FLAVOR}
    volumes:
      - /var/cert/royk.us:/var/cert/royk.us
    ports:
      - "5000:5000"
      - "9230:9229"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: ["yarn", "run", "docker:${FLAVOR}:api"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
