// flow-typed signature: 36070bbe7ef69c3a5ba960edc4067ca4
// flow-typed version: <<STUB>>/@loadable/server_v^5.13.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@loadable/server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@loadable/server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@loadable/server/lib/ChunkExtractor' {
  declare module.exports: any;
}

declare module '@loadable/server/lib/ChunkExtractorManager' {
  declare module.exports: any;
}

declare module '@loadable/server/lib' {
  declare module.exports: any;
}

declare module '@loadable/server/lib/sharedInternals' {
  declare module.exports: any;
}

declare module '@loadable/server/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@loadable/server/lib/ChunkExtractor.js' {
  declare module.exports: $Exports<'@loadable/server/lib/ChunkExtractor'>;
}
declare module '@loadable/server/lib/ChunkExtractorManager.js' {
  declare module.exports: $Exports<'@loadable/server/lib/ChunkExtractorManager'>;
}
declare module '@loadable/server/lib/index' {
  declare module.exports: $Exports<'@loadable/server/lib'>;
}
declare module '@loadable/server/lib/index.js' {
  declare module.exports: $Exports<'@loadable/server/lib'>;
}
declare module '@loadable/server/lib/sharedInternals.js' {
  declare module.exports: $Exports<'@loadable/server/lib/sharedInternals'>;
}
declare module '@loadable/server/lib/util.js' {
  declare module.exports: $Exports<'@loadable/server/lib/util'>;
}
