// flow-typed signature: 7ebec78e104ee4acf4bd30bbae7b6d79
// flow-typed version: <<STUB>>/babel-node_v^0.0.1-security/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-node' {
  declare module.exports: any;
}
