// flow-typed signature: 2577214b84d2bc06712255501c2d224c
// flow-typed version: <<STUB>>/babel-plugin-transform-imports_v^2.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-imports/babel.config' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-imports/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-imports/babel.config.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports/babel.config'>;
}
declare module 'babel-plugin-transform-imports/index' {
  declare module.exports: $Exports<'babel-plugin-transform-imports'>;
}
declare module 'babel-plugin-transform-imports/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports'>;
}
declare module 'babel-plugin-transform-imports/test/tests.js' {
  declare module.exports: $Exports<'babel-plugin-transform-imports/test/tests'>;
}
