// flow-typed signature: 82851c07972b3594fc4e35d4dc5576fa
// flow-typed version: <<STUB>>/express-jwt-authz_v^2.3.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-jwt-authz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-jwt-authz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-jwt-authz/lib' {
  declare module.exports: any;
}

declare module 'express-jwt-authz/test/index.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-jwt-authz/lib/index' {
  declare module.exports: $Exports<'express-jwt-authz/lib'>;
}
declare module 'express-jwt-authz/lib/index.js' {
  declare module.exports: $Exports<'express-jwt-authz/lib'>;
}
declare module 'express-jwt-authz/test/index.tests.js' {
  declare module.exports: $Exports<'express-jwt-authz/test/index.tests'>;
}
