// flow-typed signature: 8a7829ca1f691514d920c2ebcfe7b675
// flow-typed version: <<STUB>>/express-http-context_v^1.2.3/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-http-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-http-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-http-context/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-http-context/browser.js' {
  declare module.exports: $Exports<'express-http-context/browser'>;
}
declare module 'express-http-context/index' {
  declare module.exports: $Exports<'express-http-context'>;
}
declare module 'express-http-context/index.js' {
  declare module.exports: $Exports<'express-http-context'>;
}
