// flow-typed signature: 60c20225c9da3e0e682328118a07e6a7
// flow-typed version: <<STUB>>/https_v^1.0.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'https'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'https' {
  declare module.exports: any;
}
