// flow-typed signature: fa8491fc5dbba2c1cf3292b0a2eae83f
// flow-typed version: <<STUB>>/https_v^1.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'https'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'https' {
  declare module.exports: any;
}
