// flow-typed signature: bc55a7937ee77cfbe1d5a635db2ac9e6
// flow-typed version: <<STUB>>/jest-html-reporter_v^2.6.2/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-html-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-html-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-html-reporter/dist/main' {
  declare module.exports: any;
}

declare module 'jest-html-reporter/dist/main.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-html-reporter/dist/main.js' {
  declare module.exports: $Exports<'jest-html-reporter/dist/main'>;
}
declare module 'jest-html-reporter/dist/main.min.js' {
  declare module.exports: $Exports<'jest-html-reporter/dist/main.min'>;
}
