// flow-typed signature: 972917573db4c68090bff3ca53ecb323
// flow-typed version: <<STUB>>/webpack-stats-graph_v^1.0.8/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-stats-graph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-stats-graph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-stats-graph/index' {
  declare module.exports: $Exports<'webpack-stats-graph'>;
}
declare module 'webpack-stats-graph/index.js' {
  declare module.exports: $Exports<'webpack-stats-graph'>;
}
